### ISSUE TITLE
July 22, 2021 content changes

### ISSUE THREAD

**Issue by givp** [harmony-one/Harmony-website#1]
Requested by @stephen-tse 

- [x] move “Cross-Chain Interoperability” and “News and Progress” sections from bottom to right above of “Protocol Features”
- [x] change the middle blog “Harmony’s Strategy and Architecture” to /sushi
- [x] update videos and press to the latest top (in blue and in yellow) from /media
- [x] update newsletter from “May Update” to the latest month
- [ ] have marketingDAO vote for top 3 tweets to include
- [x] change “Scaling Ethereum Applications and Cross-Chain Finance” to “Scaling Cross-Chain Ethereum Applications”
- [x] change “Harmony’s secure bridges offer cross-chain asset transfers with Ethereum, Binance and other chains. Harmony serves as a platform for creators to connect with their community. Try our showcase below – an NFT marketplace with collectibles from hundreds of artists.” --> Harmony is your open platform for assets, collectibles, identity, governance. Our secure bridges offer cross-chain asset transfers with Ethereum, Binance and 3 other chains.

**Comment by lijiang2087** [comment]
done
